name: CI

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches: ["main"]
        paths-ignore: ["**.md", "docs/**"]

    workflow_dispatch:

jobs:
    build_and_deploy:
        timeout-minutes: 8
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "npm"
            - run: make setup
            - run: make test-nowatch
            - run: make build
            - name: Install Vercel CLI
              run: npm install --global vercel@latest
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
            - name: Deploy Project Artifacts to Vercel
              id: deploy
              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt
            - name: Extract deployment URL
              id: url
              run: echo "preview-url=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT
            - name: run e2e-test against ${{ steps.url.outputs.preview-url }}
              run: make HOST=${{ steps.url.outputs.preview-url }} test-e2e
            - uses: actions/upload-artifact@v4
              if: always()
              continue-on-error: true
              with:
                  name: test-results
                  path: test-results
