name: CI

on:
    push:
        branches: ["main"]
        paths-ignore: ["**.md", "docs/**"]

    workflow_dispatch:

jobs:
    build_and_deploy:
        timeout-minutes: 8
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "npm"
            - run: make setup
            - run: make test-nowatch
            - run: make build
            - uses: amondnet/vercel-action@v20
              id: deploy
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
                  working-directory: ./
            - name: run e2e-test against ${{ steps.deploy.outputs.preview-url }}
              run: make HOST=${{ steps.deploy.outputs.preview-url }} test-e2e
            - uses: actions/upload-artifact@v3
              if: always()
              continue-on-error: true
              with:
                  name: test-results
                  path: test-results
